name: Pulumi
on:
  push:
    branches:
      - main
jobs:
  update-infra:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
    - uses: workflow/nix-shell-action@v3
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_ACCESS_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
      with:
        packages: nodejs-19_x,wrangler,pulumi
        script: |
          cd cdk
          npm i
          pulumi stack select pub
          pulumi up -y
          cd ../client
          npm i
          npm run build
          wrangler pages publish dist --project-name=${{ secrets.PROJECT_NAME }}
