name: Pulumi
on:
  push:
    branches:
      - main
jobs:
  update:
    defaults:
      run:
        working-directory: cdk
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-node
        with:
          node-version-file: package.json
      - run: npm install
      - uses: pulumi/actions
        with:
          command: up
          stack-name: pub
        #env:
          #PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}