name: Pulumi
on:
  push:
    branches:
      - main
jobs:
  update:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
    - run: sh
    - run: nix-shell
    - run: cd cdk
    - run: pulumi up
